[iProcrastinate]
url   = "https://iprocrastinate.libsyn.com/rss"
path  = "/Users/matt/podcasts/iprocrastinate"

[alignment-newsletter]
url   = "https://alignment-newsletter.libsyn.com/rss"
path  = "/Users/matt/podcasts/alignment-newsletter"
